language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - mongodb
before_script:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &" - sleep 5
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
after_script: 
  - cat ./coverage/mocha-servertest.lcov ./coverage/karma-unittest.lcov > lcov.info
  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
